version: '3.8'
services:
  cache:
    network_mode: "host"
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6333:6333'
    command: redis-server --port 6333
    expose:
      - "6380"
    volumes:
      - cache:/data

  track_api:
    network_mode: "host"
    build:
      context: .
      dockerfile: ci/Dockerfile
      args:
        WEATHER_API_KEY: ${WEATHER_API_KEY}
        WEATHER_API_BASE_URL: ${WEATHER_API_BASE_URL}
        CACHE_TTL_IN_SECONDS: ${CACHE_TTL_IN_SECONDS}
        ENABLE_DOCUMENTATION: ${ENABLE_DOCUMENTATION}
        DEBUG: ${DEBUG}
    depends_on:
      - cache
    ports:
      - 8000:8000
    env_file:
      - .env
    container_name: track_api
    volumes:
      - .:/workspace

volumes:
  cache:
    driver: local